const { launch } = require('./harness'); const mock = require('./mock');
const S = process.env.S || __dirname + '/shots'; require('fs').mkdirSync(S, { recursive: true }); let n = 0;
(async () => {
  const h = await launch({ worker: mock.worker, port: 8767 });
  const page = h.page;
  const shot = async (name) => { n++; await page.screenshot({ path: `${S}/shots/f${String(n).padStart(2, '0')}-${name}.png` }); };
  const root = () => page.locator('div.fixed.inset-0.z-\\[90\\], div.fixed.inset-0.z-\\[95\\]').last();
  const tap = async (text) => { const b = root().getByRole('button', { name: text, exact: false }).first(); await b.click(); await page.waitForTimeout(350); };
  const step = async () => (await page.locator('.mono.text-\\[10px\\].text-neutral-600').first().innerText()).trim();
  const q = async () => (await page.locator('.dp.mt-7').first().innerText().catch(() => '')).trim();
  await page.goto('http://localhost:8767/index.html'); await page.waitForTimeout(3500);
  console.log(await step(), await q()); await shot('opener');
  await tap('Yes'); console.log(await step(), await q());
  await tap('More than once'); console.log(await step(), await q());
  await tap('On and off'); console.log(await step(), await q());
  await tap('Sometimes'); console.log(await step(), await q());
  await tap('Losing momentum'); console.log(await step(), await q()); await shot('blocker-done');
  await tap('Build muscle'); console.log(await step(), await q());
  await tap('Bigger and heavier'); console.log(await step(), await q());
  await tap('Male'); console.log(await step(), await q()); await shot('weight');
  await tap('Continue'); console.log(await step(), await q());
  await tap('1–3 years'); console.log(await step(), await q());
  await tap('I know my numbers'); console.log(await step(), await q()); await shot('numbers');
  // bump bench up a few times
  for (let i = 0; i < 6; i++) await root().getByRole('button', { name: 'More Bench press' }).click();
  await tap('Continue'); console.log(await step(), await q()); await shot('photo');
  await tap('Skip for now'); console.log(await step(), await q()); await shot('armed');
  await tap('Show my rank'); await page.waitForTimeout(400); await shot('reveal-a'); await page.waitForTimeout(1400); await shot('reveal-b');
  console.log('reveal text:', (await page.innerText('body')).match(/Your rank[\s\S]{0,80}/)?.[0].replace(/\n/g, ' '));
  await tap('See where this goes'); await page.waitForTimeout(400); await shot('projection-a'); await page.waitForTimeout(2200); await shot('projection-b');
  await tap('Continue'); console.log(await step(), await q());
  await tap('Chest'); await tap('Arms'); await shot('priorities');
  await tap('Build around'); console.log(await step()); await shot('demo-a');
  await tap("I've only got 40 min"); await page.waitForTimeout(600); await shot('demo-thinking'); await page.waitForTimeout(1500); await shot('demo-rebuilt');
  console.log('demo calls:', mock.calls.filter((c) => c.path === '/').length, 'tier hdr:', (mock.calls.find((c) => c.path === '/') || {}).headers?.['x-mi-tier']);
  await tap("That's my coach"); await page.waitForTimeout(600); await shot('plan');
  await tap('Continue'); console.log(await step(), await q());
  await tap('Lost motivation'); await tap('No time'); await shot('obstacles');
  await tap('Show me how'); console.log(await step(), await q()); await shot('induction');
  await tap('Continue'); console.log(await step(), await q());
  await tap('4'); console.log(await step(), await q()); await shot('hold-a');
  const hold = root().getByRole('button', { name: 'Hold to ignite' });
  const box = await hold.boundingBox();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.down(); await page.waitForTimeout(900); await shot('hold-b'); await page.waitForTimeout(1000); await page.mouse.up();
  await page.waitForTimeout(400); await shot('hold-c'); await page.waitForTimeout(1200);
  console.log(await step(), await q());
  await root().getByPlaceholder('Your name').fill('Max'); await root().getByPlaceholder('@yourhandle').fill('maxtest');
  await tap('Continue'); await page.waitForTimeout(800); console.log(await step()); await shot('proof');
  await tap('Continue'); console.log(await step()); await shot('timeline');
  await tap('Start my 7-day'); console.log(await step()); await shot('paywall');
  await tap('Not now'); await page.waitForTimeout(300); await shot('downsell');
  await root().getByRole('button', { name: 'Try it monthly' }).click(); await page.waitForTimeout(600); await shot('building');
  await page.waitForTimeout(1600);
  // tutorial
  for (let i = 0; i < 5; i++) { const b = page.getByRole('button', { name: /Next|Let's train/ }).first(); if (await b.count()) { await b.click(); await page.waitForTimeout(200); } }
  await page.waitForTimeout(500); await shot('train');
  console.log('errors:', page.errors.filter((e) => !/ERR_FAILED/.test(e)));
  console.log('errbox:', await page.$eval('#errbox', (e) => e.textContent));
  const settings = await page.evaluate(() => JSON.parse(localStorage.getItem('mi:mi-settings')));
  console.log('settings:', JSON.stringify({ plan: settings.plan, priorities: settings.priorities, rank: settings.rank && settings.rank.name, induction: settings.induction, trial: settings.trial, subPlan: settings.subPlan, name: settings.name, split: settings.split }));
  console.log('program:', await page.evaluate(() => { const p = JSON.parse(localStorage.getItem('mi:mi-program')); return p.name + ' | ' + p.days.map((d) => d.name + ': ' + d.exercises.map((e) => e.name).join(', ')).join(' || '); }));
  await h.close();
})().catch(async (e) => { console.error('FAIL', e.message); process.exit(1); });
